version: '2'
services:
    simpleqrapp-app:
        image: simpleqrapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://simpleqrapp-postgresql:5432/simpleQrApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    simpleqrapp-postgresql:
        extends:
            file: postgresql.yml
            service: simpleqrapp-postgresql
